# Generated by Django 4.2.9 on 2024-01-11 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0002_query_delete_querytext"),
    ]

    operations = [
        migrations.AddField(
            model_name="query", name="top_k", field=models.IntegerField(default=10),
        ),
    ]
