# Generated by Django 4.2.3 on 2023-07-06 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0002_profile"),
    ]

    operations = [
        migrations.DeleteModel(name="Profile",),
    ]
